from .gemini import (
    generate_platform_content,
    modify_content,
    analyze_content_psychology,
    generate_content_strategy,
    generate_marketing_image,
    generate_contextual_hooks,
    generate_emotional_content,
    analyze_narrative_physics,
    generate_brand_lore,
    resurrect_idea,
    analyze_why_it_works,
    generate_seo_keywords,
    perform_seo_audit,
    generate_seo_meta_tags,
    analyze_competitor_gap,
    generate_backlink_strategy,
    generate_local_seo_audit,
)

from .auth import (
    get_supabase_client,
    get_supabase_admin_client,
    get_current_user,
    require_auth,
    save_content_history,
    get_content_history,
    delete_content_history,
)

__all__ = [
    # Gemini
    "generate_platform_content",
    "modify_content",
    "analyze_content_psychology",
    "generate_content_strategy",
    "generate_marketing_image",
    "generate_contextual_hooks",
    "generate_emotional_content",
    "analyze_narrative_physics",
    "generate_brand_lore",
    "resurrect_idea",
    "analyze_why_it_works",
    "generate_seo_keywords",
    "perform_seo_audit",
    "generate_seo_meta_tags",
    "analyze_competitor_gap",
    "generate_backlink_strategy",
    "generate_local_seo_audit",
    # Auth
    "get_supabase_client",
    "get_supabase_admin_client",
    "get_current_user",
    "require_auth",
    "save_content_history",
    "get_content_history",
    "delete_content_history",
]
